---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://192.168.56.110/root/hchorfi-iot-gitlab.git
    targetRevision: main
    path: ./
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
