apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: app2
  template:
    metadata:
      labels:
        name: app2
    spec:
      containers:
      - name: openresty
        image: hchorfi/iot-ssh:v2
        ports:
          - containerPort: 80
            name: app2-http
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    name: app2
  ports:
  - name: app2-http-svc
    protocol: TCP
    port: 80
    targetPort: app2-http