Vagrant.configure("2") do |config|
  username = ENV["USER"]
  server_name = "#{username}S"
  serverw_name = "#{username}SW"
  provider = "qemu"
  
  ## qemu box for mac m1
  config.vm.box = "perk/ubuntu-2204-arm64"

  ## vbox box intel
  # config.vm.box = "focal-server"
  # config.vm.box_url = "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-vagrant.box"
  config.vm.box_check_update = false

  ## Provisioning script for bootstrapping
  config.vm.provision "shell", path: "scripts/setup.sh"
  # config.vm.provision "file", source: "configs", destination: "/configs"

  config.vm.define server_name do |server|
    ## networking (don't work for qemu)
    #server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.synced_folder "./configs", "/home/vagrant/configs", type: "smb", smb_host: "192.168.1.152"
    server.vm.hostname = server_name
    server.vm.provider provider do |prvdr|
      ## virtualbox provider option
      # prvdr.memory = 1024
      # prvdr.cpus = 1
      # prvdr.name = server_name

      ## qemu provider option
      prvdr.ssh_port = 2222
      prvdr.extra_netdev_args = "hostfwd=tcp::30008-:80,hostfwd=tcp::30007-:30007"
    end
  end

end