Vagrant.configure("2") do |config|
  username = "hchorfi"
  server_name = "#{username}S"
  serverw_name = "#{username}SW"
  
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provision "shell", path: "scripts/setup.sh"

  config.vm.define server_name do |server|
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = server_name
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = server_name
    end
  end

  config.vm.define serverw_name do |server|
    server.vm.network "private_network", ip: "192.168.56.111"
    server.vm.hostname = serverw_name
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = serverw_name
    end
  end

end
