Vagrant.configure("2") do |config|
    username = "hchorfi"
    server_name = "#{username}S"
    serverw_name = "#{username}SW"
    server_ip = "192.168.56.110"

    config.vm.box = "bento/ubuntu-22.04"
    config.vm.provision "shell", path: "scripts/setup.sh"
    config.vm.synced_folder "./configs", "/home/vagrant/configs"
  
    config.vm.define server_name do |server|
      server.vm.network "private_network", ip: server_ip
      server.vm.hostname = server_name
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 8192
        vb.cpus = 1
        vb.name = server_name
      end
    end
end