apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app1
  template:
    metadata:
      labels:
        name: app1
    spec:
      containers:
      - name: openresty
        image: openresty/openresty:buster-aarch64
        ports:
          - containerPort: 80
            name: app1-http
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/openresty/nginx.conf
        - name: nginx-default
          mountPath: /etc/nginx/conf.d/default.conf
        - name: lua-info
          mountPath: /etc/openresty/info.lua
      volumes:
      - name: nginx-default
        hostPath:
          path: /home/vagrant/configs/default.conf
      - name: nginx-conf
        hostPath:
          path: /home/vagrant/configs/nginx.conf
      - name: lua-info
        hostPath:
          path: /home/vagrant/configs/info.lua

---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    name: app1
  ports:
  - name: app1-http-svc
    protocol: TCP
    port: 80
    targetPort: app1-http
