apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app.kubernetes.io/name: app1
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: app1-http

---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app.kubernetes.io/name: app1
  ports:
  - name: app1-http-svc
    protocol: TCP
    port: 80
    targetPort: app1-http