apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app.kubernetes.io/name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app2
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
          - containerPort: 80
            name: app2-http

---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app.kubernetes.io/name: app2
  ports:
  - name: app2-http-svc
    protocol: TCP
    port: 80
    targetPort: app2-http
